---

- name: "Installing Docker Prerequisite packages"
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ docker_prerequisite_packages }}"

- name: "Configuring docker-ce repo"
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: " Installing Docker latest version"
  yum:
    name:  "{{ docker_packages }}"
    state: present

- name: " Starting and Enabling Docker service"
  service:
    name: docker
    state: started
    enabled: yes
